// <auto-generated />
using System;
using FileUploader.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileUploader.Infrastructure.Migrations
{
    [DbContext(typeof(FileUploadDbContext))]
    [Migration("20240802070659_Add tblEvent")]
    partial class AddtblEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FTPPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileNameStructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderStructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("tblClient", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("c307d31e-fb39-4b5b-824b-d38743485b0d"),
                            ClientName = "Client1",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7130),
                            FTPPassword = "Client1",
                            FTPServer = "ftp.test.com",
                            FTPUsername = "Client1",
                            FileNameStructure = "/{DocumentType_DocumentFileName}",
                            FolderStructure = "Client1/Documents/{FileNumber}",
                            IsDeleted = false,
                            ModifiedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7130)
                        },
                        new
                        {
                            ID = new Guid("e5f946ea-18c4-4c18-aa6c-cc58f5266de8"),
                            ClientName = "Client2",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7134),
                            FTPPassword = "Client2",
                            FTPServer = "ftp.test.com",
                            FTPUsername = "Client2",
                            FileNameStructure = "/{DocumentType_DocumentFileName}",
                            FolderStructure = "Client1/Documents/{FileNumber}/{DocumentType_DocumentFileName}",
                            IsDeleted = false,
                            ModifiedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7135)
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutputFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DocumentTypeCode");

                    b.ToTable("tblDocument", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.DocumentStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("tblDocumentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "ATT",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7150),
                            Description = "Document Attached",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SNT",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7151),
                            Description = "Document Sent",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "ERR",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7153),
                            Description = "Document Error",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.DocumentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("tblDocumentType", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "INV",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(8034),
                            Description = "Invoice",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "MISC",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(8036),
                            Description = "Miscellaneous Document",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SUPINV",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(8037),
                            Description = "Supplier Invoice",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "CNOTE",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(8038),
                            Description = "CreditNote",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "BLS",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(8039),
                            Description = "Billing Sheet",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("tblEvent", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.FileDocument", b =>
                {
                    b.Property<Guid>("FileID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DocumentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("FileID", "DocumentID");

                    b.HasIndex("DocumentID");

                    b.ToTable("tblFileDocument", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfDocs")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("tblFile", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFileStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblFileStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "New",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7002),
                            Description = "New File with no documents attached",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "PND",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7014),
                            Description = "File has documents attached that are ready to be sent to FTP",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SNT",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7015),
                            Description = "All documents attached to the file have been sent to FTP",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "Error",
                            CreatedDateTime = new DateTime(2024, 8, 2, 9, 6, 57, 507, DateTimeKind.Local).AddTicks(7016),
                            Description = "File has an error and not all files attached have been sent to FTP",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Document", b =>
                {
                    b.HasOne("FileUploader.Core.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.FileDocument", b =>
                {
                    b.HasOne("FileUploader.Core.Domain.Entities.Document", "Document")
                        .WithMany("FileDocuments")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FileUploader.Core.Domain.Entities.UploadFile", "File")
                        .WithMany("FileDocuments")
                        .HasForeignKey("FileID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("File");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFile", b =>
                {
                    b.HasOne("FileUploader.Core.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Document", b =>
                {
                    b.Navigation("FileDocuments");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFile", b =>
                {
                    b.Navigation("FileDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
