// <auto-generated />
using System;
using FileUploader.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileUploader.Infrastructure.Migrations
{
    [DbContext(typeof(FileUploadDbContext))]
    [Migration("20240715113101_Intial Creation of FileUploadDB and seeding the tables")]
    partial class IntialCreationofFileUploadDBandseedingthetables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FTPPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderStructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("tblClient", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("c307d31e-fb39-4b5b-824b-d38743485b0d"),
                            ClientName = "Client1",
                            CreatedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8192),
                            FTPPassword = "Client1",
                            FTPServer = "ftp.test.com",
                            FTPUsername = "Client1",
                            FolderStructure = "Client1/Documents/{FileNumber}/{DocumentType_DocumentFileName}",
                            IsDeleted = false,
                            ModifiedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8192)
                        },
                        new
                        {
                            ID = new Guid("e5f946ea-18c4-4c18-aa6c-cc58f5266de8"),
                            ClientName = "Client2",
                            CreatedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8196),
                            FTPPassword = "Client2",
                            FTPServer = "ftp.test.com",
                            FTPUsername = "Client2",
                            FolderStructure = "Client1/Documents/{FileNumber}/{DocumentType_DocumentFileName}",
                            IsDeleted = false,
                            ModifiedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8197)
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfDocs")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("tblFile", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFileStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblFileStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "New",
                            CreatedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8066),
                            Description = "New File with no documents attached",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "PND",
                            CreatedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8077),
                            Description = "File has documents attached that are pending sending to FTP",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SNT",
                            CreatedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8079),
                            Description = "All documents attached to the file have been sent to FTP",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "Error",
                            CreatedDateTime = new DateTime(2024, 7, 15, 13, 31, 1, 466, DateTimeKind.Local).AddTicks(8080),
                            Description = "File has an error and not all files attached have been sent to FTP",
                            IsDeleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
