// <auto-generated />
using System;
using FileUploader.Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileUploader.Infrastructure.Migrations
{
    [DbContext(typeof(FileUploadDbContext))]
    [Migration("20240717141740_Add Document and DocumentStatus")]
    partial class AddDocumentandDocumentStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FTPPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPServer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FTPUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FolderStructure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("tblClient", (string)null);

                    b.HasData(
                        new
                        {
                            ID = new Guid("c307d31e-fb39-4b5b-824b-d38743485b0d"),
                            ClientName = "Client1",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6589),
                            FTPPassword = "Client1",
                            FTPServer = "ftp.test.com",
                            FTPUsername = "Client1",
                            FolderStructure = "Client1/Documents/{FileNumber}/{DocumentType_DocumentFileName}",
                            IsDeleted = false,
                            ModifiedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6590)
                        },
                        new
                        {
                            ID = new Guid("e5f946ea-18c4-4c18-aa6c-cc58f5266de8"),
                            ClientName = "Client2",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6593),
                            FTPPassword = "Client2",
                            FTPServer = "ftp.test.com",
                            FTPUsername = "Client2",
                            FolderStructure = "Client1/Documents/{FileNumber}/{DocumentType_DocumentFileName}",
                            IsDeleted = false,
                            ModifiedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6594)
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentTypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutputFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DocumentTypeCode");

                    b.ToTable("tblDocument", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.DocumentStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("tblDocumentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "ATT",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6610),
                            Description = "Document Attached",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SNT",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6611),
                            Description = "Document Sent",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "ERR",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6613),
                            Description = "Document Error",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.DocumentType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Code");

                    b.ToTable("tblDocumentType", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "INV",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6838),
                            Description = "Invoice",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "MISC",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6840),
                            Description = "Miscellaneous Document",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SUPINV",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6841),
                            Description = "Supplier Invoice",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "CNOTE",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6842),
                            Description = "CreditNote",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "BLS",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6843),
                            Description = "Billing Sheet",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.FileDocument", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DocumentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("DocumentID");

                    b.ToTable("tblFileDocument", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFile", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileStatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfDocs")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("tblFile", (string)null);
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFileStatus", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.ToTable("tblFileStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "New",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6455),
                            Description = "New File with no documents attached",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "PND",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6470),
                            Description = "File has documents attached that are pending sending to FTP",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "SNT",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6471),
                            Description = "All documents attached to the file have been sent to FTP",
                            IsDeleted = false
                        },
                        new
                        {
                            Code = "Error",
                            CreatedDateTime = new DateTime(2024, 7, 17, 16, 17, 40, 706, DateTimeKind.Local).AddTicks(6472),
                            Description = "File has an error and not all files attached have been sent to FTP",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.Document", b =>
                {
                    b.HasOne("FileUploader.Core.Domain.Entities.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.FileDocument", b =>
                {
                    b.HasOne("FileUploader.Core.Domain.Entities.Document", "Documents")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("FileUploader.Core.Domain.Entities.UploadFile", b =>
                {
                    b.HasOne("FileUploader.Core.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
